#!/bin/bash
if [ -z $1 ]; then
	echo 'You must give the commit message in first parameter.'
else
	git add $PWD && git commit -m "$1" && git pull
	if [ $? = 0 ]; then
		if [ -z $2 ]; then
			git push origin master
		else
			git push origin $2
		fi
	fi
fi
